# Generated by Django 4.2 on 2023-04-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matchid", models.CharField(max_length=255)),
                ("map", models.CharField(max_length=255)),
                ("time_start", models.CharField(max_length=255)),
                ("game_length", models.CharField(max_length=255)),
                ("result", models.CharField(max_length=255)),
                ("score", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="GamePlayerInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matchid", models.CharField(max_length=255)),
                ("player_name", models.CharField(max_length=255)),
                ("player_team", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="GameRounds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matchid", models.CharField(max_length=255)),
                ("time", models.CharField(max_length=255)),
                ("event_type", models.CharField(max_length=255)),
                ("performer", models.CharField(max_length=255)),
                ("site", models.CharField(max_length=255)),
                ("weapon", models.CharField(max_length=255)),
                ("victim", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="GameStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matchid", models.CharField(max_length=255)),
                ("team", models.CharField(max_length=255)),
                ("character", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="GameTimeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matchid", models.CharField(max_length=255)),
                ("winning_team", models.CharField(max_length=255)),
                ("end_type", models.CharField(max_length=255)),
            ],
        ),
    ]
