# Generated by Django 4.2 on 2023-04-14 06:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analyzer", "0002_remove_gameinfo_id_remove_gametimeline_id_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="gamerounds",
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name="GameTimeline",
        ),
    ]
