# Generated by Django 4.2 on 2023-04-14 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("analyzer", "0003_alter_gamerounds_unique_together_delete_gametimeline"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameTimeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round", models.IntegerField(default=0)),
                ("winning_team", models.CharField(max_length=255)),
                ("end_type", models.CharField(max_length=255)),
                (
                    "matchid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analyzer.gameinfo",
                    ),
                ),
            ],
        ),
    ]
