# Generated by Django 4.2 on 2023-04-14 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("analyzer", "0004_gametimeline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamestats",
            name="id",
        ),
        migrations.AlterField(
            model_name="gamestats",
            name="matchid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="analyzer.gameinfo",
            ),
        ),
    ]
