# Generated by Django 4.2 on 2023-04-14 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("analyzer", "0005_remove_gamestats_id_alter_gamestats_matchid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gameplayerinfo",
            name="id",
        ),
        migrations.RemoveField(
            model_name="gamerounds",
            name="id",
        ),
        migrations.RemoveField(
            model_name="gametimeline",
            name="id",
        ),
        migrations.AlterField(
            model_name="gameplayerinfo",
            name="matchid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="analyzer.gameinfo",
            ),
        ),
        migrations.AlterField(
            model_name="gamerounds",
            name="matchid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="analyzer.gameinfo",
            ),
        ),
        migrations.AlterField(
            model_name="gametimeline",
            name="matchid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="analyzer.gameinfo",
            ),
        ),
    ]
