# Generated by Django 4.2 on 2023-04-14 06:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analyzer", "0006_remove_gameplayerinfo_id_remove_gamerounds_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gameinfo",
            old_name="matchid",
            new_name="matchidd",
        ),
        migrations.RenameField(
            model_name="gameplayerinfo",
            old_name="matchid",
            new_name="matchidd",
        ),
        migrations.RenameField(
            model_name="gamerounds",
            old_name="matchid",
            new_name="matchidd",
        ),
        migrations.RenameField(
            model_name="gamestats",
            old_name="matchid",
            new_name="matchidd",
        ),
        migrations.RenameField(
            model_name="gametimeline",
            old_name="matchid",
            new_name="matchidd",
        ),
    ]
