# Generated by Django 4.2 on 2023-04-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyzer", "0008_rename_matchidd_gameinfo_matchid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameplayerinfo",
            name="matchid",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="gamerounds",
            name="matchid",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="gamestats",
            name="matchid",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="gametimeline",
            name="matchid",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
